ALTER TABLE users ADD COLUMN IF NOT EXISTS onboarding_completed_steps JSONB DEFAULT '[]';
ALTER TABLE users ADD COLUMN IF NOT EXISTS onboarding_skipped BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS onboarding_finished BOOLEAN DEFAULT FALSE;
